In [2]:
import pandas as pd
menu = pd.Series(['비빔밥', '김치찌개', '된장찌개'])
price = pd.Series([10000, 9000, 8000])
# menu
price

0    10000
1     9000
2     8000
dtype: int64

In [3]:
df_from_series = pd.DataFrame({'메뉴': menu, '가격': price})
df_from_series

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [4]:
df = pd.DataFrame({
    '메뉴':  ['비빔밥', '김치찌개', '된장찌개'],
    '가격':  [10000, 9000, 8000],
    '원산지': ['국내산', '국내산', '국내산']
})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [7]:
menu_series = df['메뉴']     # Series
# menu_series
menu_df = df[['메뉴']]       # DataFrame (대괄호 2개)
menu_df

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [8]:
cols = ['메뉴', '가격']
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [9]:
print('df          :', type(df))
print("df['가격']   :", type(df['가격']))     # Series
print("df[['가격']] :", type(df[['가격']]))   # DataFrame

df          : <class 'pandas.core.frame.DataFrame'>
df['가격']   : <class 'pandas.core.series.Series'>
df[['가격']] : <class 'pandas.core.frame.DataFrame'>

In [11]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [13]:
# print(df.loc[0])          # 인덱스 0 행 전체
df.loc[df['가격'] >= 9000, ['메뉴', '가격', '원산지']]   # 가격 9000 이상

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산

In [17]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [19]:
# print(df.iloc[0])         # 0번째 행
df.iloc[0:2, 0:2]        # 앞 2행, 앞 2열

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000

In [22]:
df['할인가'] = (df['가격'] * 0.9).astype(int)   # 10% 할인 열
df

     메뉴     가격  원산지   할인가
0   비빔밥  10000  국내산  9000
1  김치찌개   9000  국내산  8100
2  된장찌개   8000  국내산  7200

In [23]:
df.loc[df['메뉴'] == '김치찌개', '가격'] = 9500   # 김치찌개 가격 변경
df

     메뉴     가격  원산지   할인가
0   비빔밥  10000  국내산  9000
1  김치찌개   9500  국내산  8100
2  된장찌개   8000  국내산  7200

In [24]:
df = df.drop(columns=['할인가'])
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9500  국내산
2  된장찌개   8000  국내산

In [26]:
df.sort_values(by='메뉴', ascending=false)   # 가격 내림차순

     메뉴     가격  원산지
1  김치찌개   9500  국내산
2  된장찌개   8000  국내산
0   비빔밥  10000  국내산

In [28]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9500  국내산
2  된장찌개   8000  국내산

In [27]:
df[(df['원산지'] == '국내산') & (df['가격'] >= 9000)]

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9500  국내산

In [29]:
df.rename(columns={'메뉴': 'menu', '가격': 'price', '원산지': 'origin'})

   menu  price origin
0   비빔밥  10000    국내산
1  김치찌개   9500    국내산
2  된장찌개   8000    국내산