In [1]:
import pandas as pd

cafe = pd.DataFrame({
    '메뉴':   ['아메리카노', '카페라떼', '녹차라떼', '자몽에이드', '레몬에이드'],
    '가격':   [4000, 4500, 5000, 5500, 5000],
    '분류':   ['커피', '커피', '논커피', '음료', '음료'],
    '재고':   [30, 12, 8, 20, 15]
})
cafe

      메뉴    가격   분류  재고
0  아메리카노  4000   커피  30
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20
4  레몬에이드  5000   음료  15

In [4]:
menu = pd.Series(['아메리카노', '카페라떼', '녹차라떼', '자몽에이드', '레몬에이드'])
price = 
menu

0    아메리카노
1     카페라떼
2     녹차라떼
3    자몽에이드
4    레몬에이드
dtype: object

In [11]:
df_from_series = pd.DataFrame({'메뉴': menu})
df_from_series

      메뉴
0  아메리카노
1   카페라떼
2   녹차라떼
3  자몽에이드
4  레몬에이드

In [13]:
menu = pd.Series(['아메리카노', '카페라떼', '녹차라떼', '자몽에이드', '레몬에이드'])
type(menu)

pandas.core.series.Series

In [14]:
df_from_series = pd.DataFrame({'메뉴': menu})
type(df_from_series)

pandas.core.frame.DataFrame

In [24]:
cafe.loc[1:3]

      메뉴    가격   분류  재고
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20

In [25]:
cafe.iloc[0:3,0:2]

      메뉴    가격
0  아메리카노  4000
1   카페라떼  4500
2   녹차라떼  5000

In [30]:
cafe['부가세'] = (cafe['가격'] * 0.1).astype(int)   # 10% 할인 열
cafe

      메뉴    가격   분류  재고  부가세    최종가
0  아메리카노  4000   커피  30  400   8400
1   카페라떼  4500   커피  12  450   9450
2   녹차라떼  5000  논커피   8  500  10500
3  자몽에이드  5500   음료  20  550  11550
4  레몬에이드  5000   음료  15  500  10500

In [31]:
cafe['최종가'] = (cafe['가격'] + cafe['부가세']).astype(int)   # 10% 할인 열
cafe

      메뉴    가격   분류  재고  부가세   최종가
0  아메리카노  4000   커피  30  400  4400
1   카페라떼  4500   커피  12  450  4950
2   녹차라떼  5000  논커피   8  500  5500
3  자몽에이드  5500   음료  20  550  6050
4  레몬에이드  5000   음료  15  500  5500

In [32]:
cafe.loc[cafe['분류'] == '음료', '재고'] = 50   # 김치찌개 가격 변경
cafe

      메뉴    가격   분류  재고  부가세   최종가
0  아메리카노  4000   커피  30  400  4400
1   카페라떼  4500   커피  12  450  4950
2   녹차라떼  5000  논커피   8  500  5500
3  자몽에이드  5500   음료  50  550  6050
4  레몬에이드  5000   음료  50  500  5500

In [34]:
# (1) 분류가 '커피'가 아니면서 가격이 5000 이상인 행만 골라라.
# (2) 그 결과를 가격 내림차순으로 정렬하라.
# (3) 정렬된 결과에서 메뉴, 가격 열만 남겨라.
cafe[(cafe['분류'] != '커피') & (cafe['가격'] >= 5000)]

      메뉴    가격   분류  재고  부가세   최종가
2   녹차라떼  5000  논커피   8  500  5500
3  자몽에이드  5500   음료  50  550  6050
4  레몬에이드  5000   음료  50  500  5500

In [36]:
cafe.sort_values(by='가격', ascending=False)

      메뉴    가격   분류  재고  부가세   최종가
3  자몽에이드  5500   음료  50  550  6050
4  레몬에이드  5000   음료  50  500  5500
2   녹차라떼  5000  논커피   8  500  5500
1   카페라떼  4500   커피  12  450  4950
0  아메리카노  4000   커피  30  400  4400